# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io" # the base hostname & protocol for the site
og_image: https://github.com/AnJoGar/AndersonJEj.github.io/blob/main/cinthia.png
google_analytics: "UA-121636368-3"
